name: 5분에 한번 uv 실행

on:
  workflow_dispatch:
  schedule:
    - cron: "5,10,15,20,25,30,35,40,45,50,55 * * * *"

jobs:
  run-uv-lock:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install uv
      - run: uv sync
      - env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: uv run main.py
